language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.4.13
  - DJANGO_VERSION=1.5.8
  - DJANGO_VERSION=1.6.5
  - DJANGO_VERSION=1.7.1
  - DJANGO_VERSION=1.8.8
  - DJANGO_VERSION=1.9.1
  - DJANGO_VERSION=1.10
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7.1
    - python: "2.6"
      env: DJANGO_VERSION=1.8.8
    - python: "2.6"
      env: DJANGO_VERSION=1.9.1
    - python: "2.6"
      env: DJANGO_VERSION=1.10
    - python: "3.4"
      env: DJANGO_VERSION=1.4.13
    - python: "3.5"
      env: DJANGO_VERSION=1.4.13
    - python: "3.5"
      env: DJANGO_VERSION=1.5.8
    - python: "3.5"
      env: DJANGO_VERSION=1.6.5
    - python: "3.5"
      env: DJANGO_VERSION=1.7.1
install:
  - pip install -r requirements.txt
  - pip install Django==$DJANGO_VERSION
  - python setup.py install
script: make test
