language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.4.22
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.7
  - DJANGO_VERSION=1.11.2
  - DJANGO_VERSION=2.0
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7.11
    - python: "2.6"
      env: DJANGO_VERSION=1.8.18
    - python: "2.6"
      env: DJANGO_VERSION=1.9.1
    - python: "2.6"
      env: DJANGO_VERSION=1.10.7
    - python: "2.6"
      env: DJANGO_VERSION=1.11.2
    - python: "2.6"
      env: DJANGO_VERSION=2.0
    - python: "2.7"
      env: DJANGO_VERSION=2.0
    - python: "3.4"
      env: DJANGO_VERSION=1.4.22
    - python: "3.4"
      env: DJANGO_VERSION=1.5.12
    - python: "3.4"
      env: DJANGO_VERSION=1.6.11
    - python: "3.4"
      env: DJANGO_VERSION=1.7.11
    - python: "3.5"
      env: DJANGO_VERSION=1.4.22
    - python: "3.5"
      env: DJANGO_VERSION=1.5.12
    - python: "3.5"
      env: DJANGO_VERSION=1.6.11
    - python: "3.5"
      env: DJANGO_VERSION=1.7.11
    - python: "3.6"
      env: DJANGO_VERSION=1.4.22
    - python: "3.6"
      env: DJANGO_VERSION=1.5.12
    - python: "3.6"
      env: DJANGO_VERSION=1.6.11
    - python: "3.6"
      env: DJANGO_VERSION=1.7.11
install:
  - pip install -r requirements.txt
  - pip install Django==$DJANGO_VERSION
  - python setup.py install
script: make test
