language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION="django>=1.4,<1.5"
  - DJANGO_VERSION="django>=1.5,<1.6"
  - DJANGO_VERSION="django>=1.6,<1.7"
  - DJANGO_VERSION="django>=1.7,<1.8"
  - DJANGO_VERSION="django>=1.8,<1.9"
  - DJANGO_VERSION="django>=1.9,<1.10"
  - DJANGO_VERSION="django>=1.10,<1.11"
  - DJANGO_VERSION="django>=1.11,<1.12"
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION="django>=1.7,<1.8"
    - python: "2.6"
      env: DJANGO_VERSION="django>=1.8,<1.9"
    - python: "2.6"
      env: DJANGO_VERSION="django>=1.9,<1.10"
    - python: "2.6"
      env: DJANGO_VERSION="django>=1.10,<1.11"
    - python: "2.6"
      env: DJANGO_VERSION="django>=1.11,<1.12"
    - python: "3.4"
      env: DJANGO_VERSION="django>=1.4,<1.5"
    - python: "3.4"
      env: DJANGO_VERSION="django>=1.5,<1.6"
    - python: "3.4"
      env: DJANGO_VERSION="django>=1.6,<1.7"
    - python: "3.4"
      env: DJANGO_VERSION="django>=1.7,<1.8"
    - python: "3.5"
      env: DJANGO_VERSION="django>=1.4,<1.5"
    - python: "3.5"
      env: DJANGO_VERSION="django>=1.5,<1.6"
    - python: "3.5"
      env: DJANGO_VERSION="django>=1.6,<1.7"
    - python: "3.5"
      env: DJANGO_VERSION="django>=1.7,<1.8"
    - python: "3.6"
      env: DJANGO_VERSION="django>=1.4,<1.5"
    - python: "3.6"
      env: DJANGO_VERSION="django>=1.5,<1.6"
    - python: "3.6"
      env: DJANGO_VERSION="django>=1.6,<1.7"
    - python: "3.6"
      env: DJANGO_VERSION="django>=1.7,<1.8"
    - python: "3.6"
      env: DJANGO_VERSION="django>=1.8,<1.9"
    - python: "3.6"
      env: DJANGO_VERSION="django>=1.9,<1.10"
    - python: "3.6"
      env: DJANGO_VERSION="django>=1.10,<1.11"
install:
  - pip install -r requirements.txt
  - pip install $DJANGO_VERSION
  - python setup.py install
script: make test
